# **Tugas 8 | Studi Kasus Heart Disease 5 Fitur | ANN**

Implementasi dengan menggunakan `ANN`

## Inisialisasi Model Dan Data ANN

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/soumya-mishra/Heart-Disease_DT/main/heart_v2.csv')
data.head()

age  sex   BP  cholestrol  heart disease
0   70    1  130         322              1
1   67    0  115         564              0
2   57    1  124         261              1
3   64    1  128         263              0
4   74    0  120         269              0

In [ ]:
data.describe()

age         sex          BP  cholestrol  heart disease
count  270.000000  270.000000  270.000000  270.000000     270.000000
mean    54.433333    0.677778  131.344444  249.659259       0.444444
std      9.109067    0.468195   17.861608   51.686237       0.497827
min     29.000000    0.000000   94.000000  126.000000       0.000000
25%     48.000000    0.000000  120.000000  213.000000       0.000000
50%     55.000000    1.000000  130.000000  245.000000       0.000000
75%     61.000000    1.000000  140.000000  280.000000       1.000000
max     77.000000    1.000000  200.000000  564.000000       1.000000

In [ ]:
data.isnull().any()


age              False
sex              False
BP               False
cholestrol       False
heart disease    False
dtype: bool

In [ ]:
nama_fitur = data.columns.copy()
nama_fitur = nama_fitur.drop('heart disease')
nama_fitur

Index(['age', 'sex', 'BP', 'cholestrol'], dtype='object')

In [ ]:
X = data.iloc[:,:4].values
y = data["heart disease"].values

In [ ]:
X

array([[ 70,   1, 130, 322],
       [ 67,   0, 115, 564],
       [ 57,   1, 124, 261],
       ...,
       [ 56,   0, 140, 294],
       [ 57,   1, 140, 192],
       [ 67,   1, 160, 286]])

In [ ]:
y

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1])

### Preprosessing Data

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = scaler.fit_transform(X)
scaled_fitur = pd.DataFrame(scaled,columns=nama_fitur)
scaled_fitur

age  sex        BP  cholestrol
0    0.854167  1.0  0.339623    0.447489
1    0.791667  0.0  0.198113    1.000000
2    0.583333  1.0  0.283019    0.308219
3    0.729167  1.0  0.320755    0.312785
4    0.937500  0.0  0.245283    0.326484
..        ...  ...       ...         ...
265  0.479167  1.0  0.735849    0.166667
266  0.312500  1.0  0.245283    0.312785
267  0.562500  0.0  0.433962    0.383562
268  0.583333  1.0  0.433962    0.150685
269  0.791667  1.0  0.622642    0.365297

[270 rows x 4 columns]

### Split data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled_fitur, y, test_size=0.2, random_state=1)
X_train.shape + X_test.shape

(216, 4, 54, 4)

### Inisialisasi Layer ANN

In [ ]:

classifier = Sequential()
classifier.add(Dense(activation = "relu", input_dim = 4, 
                     units =8, kernel_initializer = "uniform"))
classifier.add(Dense(activation = "relu", units = 14, 
                     kernel_initializer = "uniform"))
classifier.add(Dense(activation = "sigmoid", units = 1, 
                     kernel_initializer = "uniform"))
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy', 
                   metrics = ['accuracy'] )

### Train Data pada Model

In [ ]:
classifier.fit(X_train , y_train , batch_size = 8 ,epochs = 100)

Epoch 1/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6930 - accuracy: 0.5324
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.5509
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6920 - accuracy: 0.5509
Epoch 4/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6915 - accuracy: 0.5509
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6911 - accuracy: 0.5509
Epoch 6/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6908 - accuracy: 0.5509
Epoch 7/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6899 - accuracy: 0.5509
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6892 - accuracy: 0.5509
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6885 - accuracy: 0.5509
Epoch 10/100
27/27 [==============================] - 0s 2ms/step - loss: 0.6874 - accuracy: 0.5509
Epoch 11/

### Predict data With X_Test

In [ ]:

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

2/2 [==============================] - 0s 5ms/step


In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[21, 10],
       [ 6, 17]])

### Akurasi ANN

In [ ]:

accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1])
print(accuracy*100)

70.37037037037037
